add danmakustr
nostr-jp/awesome-nostr-japan pull request #74
Opened 2024-09-02 02:56 UTC by CodyTseng

Hello, I would like to introduce danmakustr, a Chrome extension that brings a niconico-style commenting experience to YouTube. In China, we refer to these comments as "弹幕" (弾幕 danmaku). Although I am not Japanese, I believe that danmakustr would be a great fit for Japanese users, and I hope more people in Japan can discover it. That's why I am submitting this PR here, hoping it will be considered for merging. 😊

![WX20240902-104724@2x](https://github.com/user-attachments/assets/042f9493-e511-407c-a97c-a15fed2b76a2)
![WX20240902-104606@2x](https://github.com/user-attachments/assets/e6aa1797-4c1f-4056-bf08-46b6c80ad1b9)

2024-09-04 23:21 UTC, ROBO358 requested changes
Thank you for the PR🫂
In this repository, do not modify `README.md` and `README-ja.md` directly, but modify `/awesome-nostr-japan.toml`. README is generated based on the TOML file.
The conversion from TOML files to Markdown is done within GitHub Actions. Check it out if you're interested.

---

I'll have to wait for someone else's review to decide whether it should be included in awesome-nostr-"japan".

2024-10-03 07:36 UTC, mattn approved these changes
I'll update README.md

2024-11-10 03:11 UTC, ROBO358 approved these changes

2024-11-10 03:12 UTC, merged

2024-11-10 03:12 UTC, ROBO358 commented
Sorry for the late approval🙇